# Generated by Django 5.1 on 2024-08-26 21:55

import posts.utils.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(upload_to=posts.utils.file_utils.image_upload_to),
        ),
    ]
